FROM apache/airflow:2.9.1

USER root

RUN apt-get update && apt-get install -y curl gnupg2 software-properties-common && \
    apt-get install -y default-jre

USER airflow

COPY my_airflow/requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt
